### PR TITLE
fix(data-warehouse): remove duplicate snowflake non-retryable test class

### PR DESCRIPTION
**Pull request by MarconLP**
## Problem

#63053 added a second `TestSnowflakeSourceNonRetryableErrors` class to `test_snowflake.py`, duplicating the existing class of the same name. Ruff now fails with `F811 Redefinition of unused TestSnowflakeSourceNonRetryableErrors` on master, which breaks the "Python code quality" check for every open PR (CI runs PRs merged with master).

## Changes

Folds the Duo Security MFA denial test from the duplicate class into the existing `TestSnowflakeSourceNonRetryableErrors` class (adopting its `source` fixture style) and deletes the duplicate. No production code changes — the Duo Security non-retryable behavior from #63053 is unchanged and still covered.

## How did you test this code?

I'm an agent; automated tests only:

- `ruff check` and `ruff format --check` on the file pass (previously failing with F811).
- `pytest posthog/temporal/data_imports/sources/snowflake/tests/test_snowflake.py -k NonRetryable` — 6 passed (disabled-user, transient-retryable, and Duo Security cases).

## Automatic notifications

- [ ] Publish to changelog?
- [ ] Alert Sales and Marketing teams?

## 🤖 Agent context

**Autonomy:** Human-driven (agent-assisted)

Authored with Claude Code (PostHog Code task). Diagnosed the master CI breakage as an F811 duplicate-class lint error introduced by #63053, merged the duplicated test into the pre-existing class rather than renaming it, and verified with ruff and pytest locally.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by MarconLP** [comment]
Closing as duplicate of #63228, which takes the same approach and already has approvals.
