### PR TITLE
feat(quill): add Heatmap chart to quill-charts

### PR DESCRIPTION
**Pull request by jonmcwest**
## Problem

`@posthog/quill-charts` has no 2D density chart. The tracing product needs a latency-over-time heatmap (time buckets × log duration buckets, count as color) – the canonical APM view for spotting bimodal latency bands, drift, and where slow outliers sit in time. A stacked sparkline and a static histogram can't show any of that.

This is the second PR in that series (the backend endpoint is [#71555](https://github.com/PostHog/posthog/pull/71555)); the product wiring lands separately, so nothing ships to users yet.

## Changes

- New `Heatmap` chart in `packages/quill/packages/charts/src/charts/Heatmap/`, built on the exported core `Chart` seams (`createScales` / `drawStatic` / `drawHover` / `wrapClickData`) – the same adapter pattern as `BoxPlot`.
- API: `xLabels` × `yLabels` (row 0 at the bottom), dense `cells[row][col]` counts, one accent color with an alpha ramp (`log1p` normalization by default, `colorScale: 'linear'` opt-out), `onCellClick`, custom `tooltip` render prop.
- Categorical y-axis rides the existing numeric tick machinery: ticks are row-center values (`i + 0.5`) with a formatter mapping back to row labels, and a synthetic `valueRangeSeries` makes `useChartMargins` measure the gutter against real labels instead of cell counts.
- Single-cell tooltip (`HeatmapTooltip`): each adapter row carries its cell's exact pixel range via `resolvePositionValue`/`resolveBottomValue`, so the existing `findClosestSeriesKey` containment pass resolves the hovered cell. `cursor` tooltip placement so it tracks the cell, not the column top.
- Pure grid math in `heatmap-layout.ts` (layout, bottom-up row mapping, count normalization, color ramp).
- Stories (latency demo with a deliberately bimodal shape, linear scale, clickable cells), exports in `src/index.ts`, and the `AGENTS.md` chart table row.

No brush/drag selection yet – a 2D `onAreaSelect` extension of `useDragToZoom` is the next PR in the series.

### Screenshots (Storybook, run on a devbox)

The `LatencyOverTime` story – deterministic bimodal data: a fast band all day plus a slow band appearing mid-window, the shape a latency heatmap exists to reveal. Log color ramp keeps the long tail visible:

Heatmap latency-over-time story

Per-cell hover: the cursor-y narrowing resolves the single hovered cell (outline) and the built-in tooltip shows column label / row label / count:

Heatmap single-cell tooltip

## How did you test this code?

- `jest src/charts/Heatmap` under the frontend jest project – 11 passed.
- `heatmap-layout.test.ts`: bottom-to-top row orientation round-trip (`cellRect` ↔ `rowAtY`) – flipping this silently inverts every tooltip/hover/brush mapping downstream; parameterized `normalizeCount` cases guard the log/linear ramp and the zero-count/zero-max edge (`log10(0)` washout).
- `Heatmap.test.tsx`: y ticks render row *labels* not raw row-unit numbers – the categorical-axis-over-numeric-machinery adapter is the riskiest part of this PR; plus a ragged-grid input case that must not desync the axis.
- Heatmap source files typecheck clean; visual review via the three new storybook stories.

## Automatic notifications

- [ ] Publish to changelog?
- [ ] Alert Sales and Marketing teams?

## Docs update

Updated `packages/quill/packages/charts/AGENTS.md` (chart table) in this PR.

## 🤖 Agent context

**Autonomy:** Human-driven (agent-assisted)

Authored with PostHog Code (Claude), following the quill charts package conventions (AGENTS.md read first; story + jsdom tests + guide row in the same PR).

Decisions: canvas rendering on core `Chart` rather than reusing the DOM-table `TwoDimensionalHeatmap` from DataVisualization (wrong layer, insight-specific); a single-accent alpha ramp via `dimColor` instead of a multi-stop palette so density reads on light and dark without new tokens; log1p count normalization by default because latency count grids are long-tailed and a linear ramp washes out everything but the mode.

---
*Created with [PostHog Code](https://posthog.com/code?ref=pr)*

### CODE REVIEW

**Comment by jonmcwest** [comment]
## 🧹 Polish pass (simplify + code-review)

Ran `/polish` (simplify then high-effort code-review) over the diff and pushed the fixes in [`03d5a5e`](https://github.com/PostHog/posthog/commit/03d5a5e60183262d7e902ab5d91cfda9cf7b7413). Scoped to the three Heatmap source files.

### Applied

- **`Heatmap.tsx` — unused `createScales` param.** `coloredSeries` was declared but never read; `tsgo` flagged it (`TS6133`), which is what failed **Frontend typechecking** and **Frontend Tests Pass**. Renamed to `_coloredSeries`.
- **`heatmap-layout.ts` / `Heatmap.tsx` — per-cell color re-parse in the draw loop.** `heatmapCellColor(accent, t)` re-parsed the accent string via d3-color for every non-empty cell (hundreds per redraw, on every prop/theme/resize change). Replaced with a `createCellColorRamp(accent)` factory built once per `drawStatic` that parses the accent once and memoizes fills by 8-bit alpha (the finest a canvas can resolve). Output is visually identical.
- **`HeatmapTooltip.tsx` — inline styles.** Two `style={{}}` blocks carried `eslint-disable react/forbid-dom-props`, against the quill "use Tailwind utility classes exclusively — no inline styles" rule. The sibling `BoxPlotTooltip` / `DefaultTooltip` do the same static layout with plain classes, so swapped to `flex items-center gap-1.5` / `ml-auto pl-3` and dropped the disables.

### Considered, not applied

- **Categorical y-axis tick thinning** (`AxisLabels`/`computeVisibleYTicks`). The heatmap rides the numeric tick machinery, so a tall grid (more rows than fit at ~16px each) would have row labels thinned by the numeric "1-2-5 roundness" heuristic in an arbitrary order rather than an even/edge-preserving one. The clean fix is a categorical-axis mode (or a `keepAllTicks` escape hatch) in the core `Chart`/`AxisLabels` seam — a shared-infra change well outside this diff that would affect every chart. Flagging for a follow-up, not something to bandaid here.
- **`wrapClickData` row-0 fallback.** When the cursor row can't be resolved, `wrapClickData` returns the base chart's row-0 payload. Traced the interaction path: hover state is only set inside `isInPlotArea`, and clicks only fire when `hoverIndex >= 0`, so the click cursor is always within the plot and `rowAtY` always resolves a valid row — the fallback is unreachable defensive code, not a live bug. Left as-is.
- **Negative / oversized `cells` input** silently drops those cells. Consistent with the documented "0 or missing = empty" contract; left as-is.

### Verification

- `jest packages/quill/**/Heatmap` — **11 passed**
- `tsgo --noEmit` — **0 errors** in the Heatmap files (the original `TS6133` is gone)
- `oxlint` clean; `oxfmt` applied to the touched files

**Comment by jonmcwest** [comment]
### CI fix: unrelated `issuesDataNodeLogic.tsx` change

Heads up on the one non-Heatmap file in this diff. After merging master, **Frontend typechecking** started failing with:

```
products/error_tracking/frontend/logics/issuesDataNodeLogic.tsx(8,5): error TS6196: 'AnyResponseType' is declared but never used.
```

This is a master-side breakage from the in-flight inline-Kea-types migration, not from the Heatmap work — the file is byte-identical to `origin/master`. `kea-typegen` now expands the inline `setResponse` parameter from `Exclude<AnyResponseType, undefined>` to the explicit response union, which orphans the `AnyResponseType` type import, and tsgo (`noUnusedLocals`) fails the whole frontend typecheck.

The fix inlines the resolved union (identical to `typegen:write`'s output and to the existing return type) and drops the unused import, so the file is idempotent under `typegen:write`. Verified locally: `typegen:write` + `tsgo --noEmit` no longer reports the error and leaves the change in place.

Happy to drop this from the PR once master is green again if the migration lands its own fix.

<sub>🦉 via [talyn.dev](https://talyn.dev)</sub>

File: packages/quill/packages/charts/src/charts/Heatmap/Heatmap.tsx [hunk 1]
```diff
@@ -0,0 +1,340 @@
...
+    theme,
+    config,
+    tooltip,
+    onCellClick,
+    className,
+    dataAttr,
+    children,
+}: Omit<HeatmapProps, 'onError'>): React.ReactElement {
+    const { colorScale = 'log' } = config ?? {}
+    const accent = config?.color || theme.colors[0] || '#1d4aff'
```
[the remark this answers is not in the document]
Comment (jonmcwest) [reply packages/quill/packages/charts/src/charts/Heatmap/Heatmap.tsx]: Fixed in d5ed996. The accent is now resolved through a new `resolveCssColor` helper before it reaches the canvas, so a `var(--…)` accent (e.g. `var(--data-color-1)`) is turned into a concrete color that `dimColor`/`fillStyle` can use — cells keep their alpha ramp instead of rendering blank. The memo re-resolves on light/dark flips (it depends on `theme.colors`). Non-`var()` accents and no-DOM contexts pass through unchanged.

<sub>🦉 via [talyn.dev](https://talyn.dev)</sub>

File: packages/quill/packages/charts/src/charts/Heatmap/Heatmap.tsx [hunk 2]
```diff
@@ -0,0 +1,340 @@
...
+    )
+
+    const createScales: CreateScalesFn = useCallback(
+        (_coloredSeries: ResolvedSeries[], scaleLabels: string[], dimensions: ChartDimensions): ChartScales => {
+            const layout = computeHeatmapLayout(dimensions, scaleLabels.length, yLabels.length)
+            const labelIndex = new Map(scaleLabels.map((label, i) => [label, i]))
+            const priv: HeatmapPrivate = {
+                __heatmap: { layout, cells: grid, accent, maxValue, colorScale },
+            }
+            return {
```
[the remark this answers is not in the document]
Comment (jonmcwest) [reply packages/quill/packages/charts/src/charts/Heatmap/Heatmap.tsx:197]: Fixed in d5ed996. Columns are now keyed by index (`columnKeys = xLabels.map((_, i) => \`${i}\`)`) rather than by label text before they reach the base chart's label-keyed interaction/tick layer — the same band-key-by-index pattern `FunnelChart` uses for repeated step names. Repeated `xLabels` no longer collapse onto one x position, so hover, tooltip, and click resolve the correct column. Formatters map the per-column keys back to the display label (x-axis ticks, tooltip header, and the `onCellClick` `xLabel`), so the public tooltip/click contract is unchanged. Added a regression test that a duplicated column label renders as distinct x-axis ticks.

<sub>🦉 via [talyn.dev](https://talyn.dev)</sub>

**Comment by jonmcwest** [comment]
Both greptile P1 review threads are addressed and resolved (commit d5ed996):

- **CSS-variable accent** — added `resolveCssColor`, applied to the heatmap accent so a `var(--…)` color is resolved to a concrete value before it reaches the canvas (previously blanked non-empty cells).
- **Duplicate x-labels** — columns are now keyed by index (the same band-key-by-index pattern `FunnelChart` uses), so repeated `xLabels` no longer collapse; formatters map keys back to the display label, keeping the tooltip/click contract unchanged.

Both fixes have regression tests; all 23 charts unit tests pass, build typecheck and lint are clean. Branch has been brought up to date with master via a signed merge (no conflicts, no unrelated files in the diff).

**CI status:** all automated checks are green — including the full 16-shard chromium visual-regression matrix, backend, lint, and typecheck. The remaining red checks are the **PostHog Visual Review** gate ("6 new") and the required code review, both of which need a human:

- The 6 visual changes are all **new** snapshots (none are *changed*), i.e. the new Heatmap stories that this PR adds — they need approval in the Visual Review UI, they aren't a regression.
- `REVIEW_REQUIRED` needs an approving code review.

I can't resolve either of those myself, so I'm stopping here. Everything within my control is green.

<sub>🦉 via [talyn.dev](https://talyn.dev)</sub>

**Comment by jonmcwest** [comment]
CI fix: unrelated `featurePreviewsLogic.tsx` typegen drift

The `Frontend typechecking` job failed on the `schema:build:json` + `git diff --exit-code` step, flagging `frontend/src/layout/FeaturePreviews/featurePreviewsLogic.tsx` — its inline kea-typegen interfaces were stale (the Coming Soon waitlist survey work added concept-survey actions, a reducer value, and a selector without regenerating them). This drift is already present on `master`, so it lands on any branch that merges master; it is unrelated to the heatmap chart.

Regenerated the inline types in `539c9d9` (the file now hashes to exactly what kea-typegen produces), which clears the check.

<sub>🦉 via [talyn.dev](https://talyn.dev)</sub>

**Review by adamleithp — COMMENTED** [review]
@sampennington you should have a look

**Comment by jonmcwest** [comment]
@posthog-bot this needs a screenshot

**Review by adamleithp — APPROVED** [review]
PR needs screenshots!! But approved to unblock

**Comment by jonmcwest** [comment]
CI note: flaky Playwright E2E, unrelated to this PR

The `Playwright E2E tests` job flaked on two consecutive runs, each failing a **different** unrelated test:
- attempt 1: `SQL Editor › Basic flow › Save view`
- attempt 2: `Notebooks › Add a trend insight, expand it, verify data, and filter by date range` — this one is already tracked as flaky in Trunk

Neither touches the quill charts package this PR changes (172/173 passing on attempt 2). Re-running to get a clean pass; the root cause sits in those scenes, not here.

<sub>🦉 via [talyn.dev](https://talyn.dev)</sub>

File: packages/quill/packages/charts/src/charts/Heatmap/HeatmapTooltip.tsx [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+                <span data-attr="hog-chart-tooltip-series" className="truncate">
+                    {entry.series.label}
+                </span>
+                <strong data-attr="hog-chart-tooltip-value" className="tabular-nums ml-auto pl-3">
+                    {valueFormatter ? valueFormatter(entry.value) : entry.value.toLocaleString()}
+                </strong>
+            </div>
+        </TooltipSurface>
+    )
+}
```
Comment (sampennington) [inline packages/quill/packages/charts/src/charts/Heatmap/HeatmapTooltip.tsx]: i think this is quite similar to the default tooltip, could you just use:
```
const key = ctx.hoverPosition ? findClosestSeriesKey(ctx.seriesData, ctx.hoverPosition.y) : null
const entry = ctx.seriesData.find((s) => s.series.key === key)
if (!entry) {
    return null
}
return (
    <DefaultTooltip
        {...ctx}
        label={resolveColumnLabel(ctx.label)}
        seriesData={[entry]}
        labelFormatter={tooltipLabelFormatter}
        valueFormatter={tooltipValueFormatter}
    />
)
```

In the main component and not build a separate tooltip?

**Review by sampennington — APPROVED** [review]
Looks good! Just a tooltip suggestion

File: packages/quill/packages/charts/src/charts/Heatmap/HeatmapTooltip.tsx (hunk 3 above)
Comment (jonmcwest) [reply packages/quill/packages/charts/src/charts/Heatmap/HeatmapTooltip.tsx]: Good call — done in 96937c5fbe8. `renderTooltip` now narrows `seriesData` to the hovered entry (same `findClosestSeriesKey` containment) and renders `DefaultTooltip` with it, exactly as you sketched; `HeatmapTooltip.tsx` is deleted. One small deviation from the snippet: the label re-mapping happens on the context before the branch (`mapped = { ...ctx, label: resolveColumnLabel(ctx.label) }`) so a consumer-supplied `tooltip` render prop gets the display label too, not just the default path. Net −26 lines, and the tooltip now speaks DefaultTooltip's `data-attr` testing contract for free.
