### PR TITLE
Remove mutable dataclasses

### PR DESCRIPTION
**Pull request by guidoiaquinti**
## Changes
This PR removes all the mutable dataclasses definitions in our codebase and by using `frozen=True` we make the dataclasses immutable and hashable.

Disclaimer: I'm pretty new to dataclasses in general as they were introduced in Python 3.7 and the last time I worked in Python I was using the old 2.7 version. 
 
## How did you test this code?
CI should be ✅

### CODE REVIEW

**Review by hazzadous — APPROVED** [review]
I'm in favour of making these "immutable". fingers crossed our code coverage is good enough to catch issues with this. Do you know if mypy can check if all is well here?

**Comment by guidoiaquinti** [comment]
> fingers crossed our code coverage is good enough to catch issues with this. Do you know if mypy can check if all is well here?

Same feeling here 😅  I've checked `mypy` and it found 221 errors in 52 files but nothing related to this change.

@macobo what do you think about this?

**Comment by hazzadous** [comment]
> Same feeling here 😅 I've checked `mypy` and it found 221 errors in 52 files but nothing related to this change.

```
@hazzadous ➜ /workspaces/posthog (dataclass ✗) $ mypy .
Running in test mode. Setting DEBUG and TEST environment variables.

🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻
Skipping async migrations setup. This is unsafe in production!
🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺

ee/clickhouse/queries/experiments/funnel_experiment_result.py:108: error: Property "key" defined in "Variant" is read-only
posthog/internal_metrics/test/test_internal_metrics.py:105: error: Argument 1 to "len" has incompatible type "object"; expected "Sized"
Found 2 errors in 2 files (checked 783 source files)
```

I gather we still wouldn't get immutability of, e.g., a list attribute which is annoying or dict etc. I suspect that this type of situation is the more common source of issues with mutations. I'm thinking the whole typescript argument over `const` not really making the structure immutable, there we at least have [`as const`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions) which I don't think we have a related thing in python.

The only other thing I was wanting was a simple way to copy a dataclass but with updated attributes, it's not totally obvious but using `replace()` looks like the way to do this. Not sure how many people will know how to do this, I ended up looking in [here](https://rmcomplexity.com/article/2021/01/04/everything-you-need-to-know-about-dataclasses.html#updating-an-object-instance-by-replacing-the-entire-object).

I'm down for the change, it's easy to back out if we have issues.
