### PR TITLE
feat(data-warehouse): implement metaplane import source

### PR DESCRIPTION
**Pull request by Gilbert09**
## Problem

Metaplane by Datadog is a data observability platform that anomaly-monitors warehouse tables and columns. Data teams want its monitor metadata and evaluation history in the warehouse to report on data-quality SLAs, track when monitors ran, and analyze pass/fail rates and expected-vs-actual bounds over time. The source was scaffolded (hidden, empty fields) in #71137 but had no sync logic.

**Why:** fills in one of the scaffolded eng/support sources so Metaplane users can actually connect it and query their data-quality history in PostHog.

## Changes

Implements the Metaplane source end to end, following the `source.py` / `settings.py` / `metaplane.py` architecture contract, and ships it visible with `releaseStatus=ReleaseStatus.ALPHA` (the scaffold's `unreleasedSource=True` is removed).

Four tables, all verified against the current public API reference (`https://dev.api.metaplane.dev/v1`, raw API key in the `Authorization` header):

| Table | Endpoint | Sync |
| --- | --- | --- |
| `connections` | `GET /v1/connections` | full refresh |
| `monitors` | `GET /v1/monitors/connection/{id}` per connection | full refresh |
| `monitor_evaluations` | `POST /v1/monitors/evaluation-history/{id}` per monitor | incremental on `createdAt` |
| `connection_sync_statuses` | `GET /v1/connections/{id}/sync/status` per connection | full refresh |

Design notes:

- `ResumableSource`: the evaluation fan-out bookmarks the current monitor id plus its `createdAt` cursor in Redis (saved after each yielded page), so a heartbeat-timeout resume picks up mid-monitor instead of restarting the whole fan-out.
- Evaluations carry no id of their own, so the primary key is the injected `monitorId` plus `createdAt`, and the table partitions on `createdAt` (stable). `sort_mode="desc"` for the fan-out so the incremental watermark persists only at successful job end - mid-run, monitor B's old rows arrive after monitor A's new ones.
- Incremental is server-side: the evaluation-history endpoint accepts a `createdAt` cursor with `sortOrder=ASC` and `limit` up to 500. A cursor non-advance guard stops pagination if a full page shares one timestamp (the docs don't state cursor inclusivity), and the schema is merge-only (no append) for the same reason.
- Tag endpoints are excluded: the API only returns tag data for tag names you already know, with no way to enumerate them. The Ingest Datapoint endpoint is private beta.
- All HTTP goes through `make_tracked_session()`; 404s mid-fan-out (deleted connection/monitor) are skipped, 429/5xx retried via tenacity, 401/403 registered as non-retryable errors.
- `canonical_descriptions.py` documents every table/column from the official API reference, and `lists_tables_without_credentials = True` feeds the public docs table catalog.

> [!NOTE]
> I could not curl the live API with real credentials (none available), so endpoint request/response shapes come from the vendor's OpenAPI reference plus an unauthenticated probe (confirms 401 behavior). The undocumented bits - evaluation cursor inclusivity, ordering of the monitor list - are handled conservatively (merge-only sync, non-advancing-cursor guard, id-based resume bookmark) and noted in code comments.

The user-facing doc lives at `metaplane/docs/metaplane.mdx` in the batch's convention (no posthog.com checkout in this environment); it needs to move to `posthog.com/contents/docs/cdp/sources/metaplane.mdx`, after which `audit_source_docs` should pass. The icon (`metaplane.png`) already landed with the scaffold.

## How did you test this code?

- `pytest products/.../sources/metaplane/tests` - 46 tests pass. `test_metaplane.py` covers the transport: evaluation pagination requests the next page from the last row's `createdAt` and stops on short pages (guards page-boundary skips), the non-advancing-cursor guard (guards an infinite pagination loop), incremental watermark seeding the initial cursor (guards full re-fetch on every incremental sync), resume skipping completed monitors and honoring the saved cursor (guards duplicate/lost work on resume), 404 skips mid-fan-out (guards one deleted monitor failing the whole sync), and the bare-key `Authorization` header (a Bearer prefix would break auth). `test_metaplane_source.py` covers schema flags (merge-only, incremental only where the server filters), credential validation mapping, and pipeline argument plumbing.
- Cross-source suites (`test_generated_configs.py`, `test_source_categories.py`) pass; the two `test_stripe_config` failures pre-exist on the base branch.
- `ruff check` / `ruff format` clean; `hogli ci:preflight --fix` reports 0 failures.
- Not done: no live sync against a real Metaplane account (no credentials in this environment).

## Automatic notifications

- [ ] Publish to changelog?
- [ ] Alert Sales and Marketing teams?

## Docs update

Doc added in-repo at `metaplane/docs/metaplane.mdx` (canonical template, `<SourceParameters />` + `<SourceTables />`); needs to land in the posthog.com repo as noted above.

## 🤖 Agent context

**Autonomy:** Fully autonomous

Implemented with Claude Code. Skills invoked: `/implementing-warehouse-sources` (architecture contract, incremental/resume rules), `/writing-tests` (test value gate), `/documenting-warehouse-sources` (doc template). Endpoint shapes were researched from Metaplane's published OpenAPI reference (docs.metaplane.dev) and an unauthenticated probe of the live API. Square was used as the reference implementation (modern ResumableSource yielding `list[dict]`, no source-level batcher); Klaviyo's list fan-out informed the monitor-id resume bookmark and desc-mode watermark handling. Rejected the generic `rest_source.RESTClient` path because evaluation history paginates via a POST body cursor, which fits hand-rolled `requests` better.

---
*Created with [PostHog Code](https://posthog.com/code?ref=pr)*

### CODE REVIEW

**Comment by Gilbert09** [comment]
CI fix pushed: all five warehouse-sources shards were failing at collection (and mypy on the same lines) because the scaffold branch's bulk `generate:source-configs` run reverted `StripeAuthMethodConfig` to the generator's raw output, which marks select-option child fields as required. Master's committed version keeps them optional (an OAuth-connected Stripe source submits no `stripe_secret_key`), and `test_stripe_source.py` / `test_generated_configs.py::test_stripe_config` encode that contract. Restored the class to master's version in 2b7ca93.

Note for the base PR (#71137): the same drift exists on `tom/scaffold-100-eng-support-sources` itself, so other PRs stacked on it will hit the same failure until this lands or the base picks up the same one-class restore. Longer term the generator should emit select-option children as optional so regeneration stops reverting the hand-fix.

**Review by danielcarletti — APPROVED** [review]
LGTM

**Comment by Gilbert09** [comment]
This finding is on `posthog/temporal/ai/slack_app/activities/task_creation.py`, which is not part of this PR — as the warning notes, the flagged line isn't in the diff. This PR only adds a new data-warehouse import source under `products/warehouse_sources/backend/temporal/data_imports/sources/metaplane/`. The Slack Connect approval-gate concern is pre-existing code on `master` and out of scope here; it should be triaged against the PR that actually touches `slack_app`.

<sub>🦉 via [talyn.dev](https://talyn.dev)</sub>

**Comment by Gilbert09** [comment]
This finding points at `posthog/temporal/ai/slack_app/activities/task_creation.py:652`, which isn't part of this PR — the diff here is limited to the new Metaplane data-warehouse source under `products/warehouse_sources/backend/temporal/data_imports/sources/metaplane/` (plus the generated `generated_configs.py` and `SOURCES.md`). The bot itself notes the flagged line "is not part of the diff"; it's picking up code that already lives on `master`, so it's out of scope for this change and will need to be addressed against the Slack app code directly.

<sub>🦉 via [talyn.dev](https://talyn.dev)</sub>

**Comment by Gilbert09** [comment]
This finding is on `posthog/temporal/ai/slack_app/activities/task_creation.py`, which is not part of this PR — as the bot itself notes, the flagged line "is not part of the diff." This PR only adds the Metaplane data-warehouse import source (`products/warehouse_sources/.../metaplane/*` plus a one-field config change). Nothing here touches Slack Connect permission gating, so there's no action to take on this branch.

<sub>🦉 via [talyn.dev](https://talyn.dev)</sub>

**Comment by Gilbert09** [comment]
**Heads-up on CI (posted by automation).**

CI on this branch keeps getting cancelled before it can finish, so the checks never settle green — but the cause is churn, not the change itself:

- The branch is being brought up to date with `master` repeatedly, and `master` is very active right now. Each "update from master" merge lands before the ~30-minute CI run completes, which cancels the in-flight runs; a fresh run starts on the new merge commit, and the cycle repeats. I've watched this happen across several consecutive merge commits.
- On every commit so far, every check that actually ran to completion **passed**. The only red checks have been the aggregate "… Tests Pass" gate jobs, which report failure when their upstream matrix jobs are *cancelled* — not because any test failed.
- The change is otherwise ready: approved, mergeable, with a clean diff limited to the new Metaplane source. The source's tests pass locally (`test_metaplane.py`, `test_metaplane_source.py`, plus the shared `test_generated_configs.py` / `test_source_config_generator.py`), and `ruff check`/`format` are clean.

To reach a green run, the branch needs a quiet ~30-minute window without a new master-merge so CI can complete on a stable commit. It looks like the branch is being auto-updated very frequently (possibly by more than one updater at once); pausing branch auto-updates — or letting a single updater own it — should let the checks settle. I'm holding off on any further merges/pushes so as not to add to the churn.

<sub>🦉 via [talyn.dev](https://talyn.dev)</sub>

**Comment by Gilbert09** [comment]
This finding is on `posthog/admin/admins/data_deletion_request_admin.py`, which is not part of this PR — the diff here is limited to the new Metaplane data-warehouse source under `products/warehouse_sources/.../metaplane/` (the bot notes it could not attach inline because the line is not in the diff). Nothing in this PR touches deletion-request approval logic, so there is no change to make here. If the auto-approval concern is valid on `master`, it should be tracked separately against that code rather than on this source-addition PR — same as the earlier out-of-scope finding on `slack_app/activities/task_creation.py`.

<sub>🦉 via [talyn.dev](https://talyn.dev)</sub>

**Comment by Gilbert09** [comment]
### Status: code-complete and verified; CI blocked by head-churn cancellations

This PR is approved, mergeable, and `0` commits behind master. The metaplane source verifies cleanly locally:

- `ruff check` / `ruff format` — clean
- `mypy --cache-fine-grained` on `metaplane/{metaplane,source,settings}.py` — no issues
- `test_metaplane.py` + `test_metaplane_source.py` (46 tests) and `sources/tests/test_generated_configs.py` (28 tests) — pass
- Repo-check scripts reproduced locally all pass: `check-dwh-source-agnostic.py`, `check-operator-parity.py`, `check-version-specifiers.py`, `tach check --dependencies --interfaces`, `lint-imports`; `generated_configs.py` is in sync

The only red is the **Dagster Tests Pass** gate, and it's a cancellation artifact rather than a real failure. On each attempt the Dagster jobs — including *"Determine need to run dagster checks"* — are **cancelled** mid-run, so the gate reports failure instead of skipping. This PR touches only `products/warehouse_sources/...` and no Dagster paths, so a run that completes skips Dagster and the gate goes green (as it did on this branch's 2026-07-15 runs, where both Backend CI and Dagster CI passed).

The cancellations come from the branch head being rewritten repeatedly by "Update branch" merges as master advances — each new head restarts CI via concurrency before the prior run finishes. Over the course of this session the head cycled through many merge commits every few minutes, faster than a Dagster (~5 min) or Backend CI (~20 min) run can complete.

No code change is needed. It just needs one CI run to complete without a mid-flight head update — i.e. a calmer master window, or a maintainer re-running the cancelled Dagster workflow / merging (the failing check is a cancellation artifact).

<sub>🦉 via [talyn.dev](https://talyn.dev)</sub>

**Comment by Gilbert09** [comment]
### Status: code-complete and approved, but CI cannot finish due to rapid branch updates

This PR is functionally ready:

- The Metaplane source is implemented and its tests pass locally — `products/warehouse_sources/backend/temporal/data_imports/sources/metaplane/tests/` (46 tests), plus `ruff check`, `ruff format --check`, and `mypy` all clean on the new module.
- The review is approved and there are no unresolved review threads.
- Squash **auto-merge is enabled**.
- I could not find any genuine CI test failure — every red check I inspected was a gate job reporting `failure` because its underlying job was **cancelled**, not because a test failed. The `warehouse-sources` product-test shards were passing (4/5 and 5/5 green) before being cancelled.

**The blocker:** the branch is being force-pushed (re-merging `master`) very frequently — as often as every 1–6 minutes in bursts. Each force-push starts a fresh CI run and cancels the in-flight one. The backend/dagster test matrix takes ~30 minutes, so it never reaches completion before the next force-push cancels it. In the one ~33-minute stable window (head `ed5373f8d4`), the Django/Dagster shards ran for ~29 minutes and were then cancelled ~4 minutes short of finishing. Because required checks never complete green on a stable head, the enabled auto-merge never has a chance to fire.

**What's needed:** pause the branch-update automation for this PR long enough (~30 min) for a single CI run to finish. Since branch protection here does not require the branch to be up to date (the PR never shows `behind`, only `blocked`/`unstable`) and auto-merge uses squash, the frequent re-merging of `master` isn't necessary for merge and is what's preventing CI from completing. Once one run finishes green, auto-merge should merge it automatically.

I've left auto-merge enabled so it will still merge on its own if a long-enough gap between updates occurs.

<sub>🦉 via [talyn.dev](https://talyn.dev)</sub>

**Comment by Gilbert09** [comment]
Heads up on the one non-Metaplane file in this PR: `products/exports/.../test/test_report_pipeline.py`.

The `Python code quality` (mypy) check was failing on an error inherited from `master`, not from this change:

```
test_report_pipeline.py:487: error: Missing named argument "relevant_events" for "_plan_to_freeze"
```

This is a semantic merge conflict on `master`: [#71834](https://github.com/PostHog/posthog/pull/71834) made `relevant_events` a required keyword-only arg of `_plan_to_freeze`, while [#71837](https://github.com/PostHog/posthog/pull/71837) added `test_plan_to_freeze_requires_no_failures` on an earlier base that didn't pass it. Both were green independently; combined on `master` they break mypy, so every PR rebased/merged past that point inherits the failure.

Fixed it here so this PR can go green — the test now passes `relevant_events` and asserts it in the frozen envelope. Happy to split it into its own PR if preferred.

<sub>🦉 via [talyn.dev](https://talyn.dev)</sub>

**Comment by Gilbert09** [comment]
**Automated PR-tending status**

The Metaplane source implementation itself is in good shape:

- All 46 Metaplane tests pass locally (`test_metaplane.py`, `test_metaplane_source.py`).
- The PR is approved, has no outstanding review threads, and is mergeable with a clean diff (only the `metaplane/` source files plus `generated_configs.py` and `SOURCES.md`).
- CI reached fully green earlier on an un-superseded commit (`1a028f3c`), so the checks do pass when a run is allowed to finish.

The remaining blocker is not the code — it's CI churn. The branch is being re-merged with `master` every few minutes to keep it current, and each update cancels the in-flight CI run via concurrency. The long-running jobs (Dagster, warehouse-sources product tests) take longer than the gap between updates, so they never finish. Every "failure" observed since has been a cascade cancellation of the `Dagster Tests Pass` gate (its shard jobs were cancelled, not failed), not a real test failure.

Recommendation: pause the automatic base-branch updates on this PR (or wait for `master` to quiet down) so one CI run can complete end-to-end. The enabled auto-merge will then land it. I'm intentionally not pushing further base merges, since additional updates would only prolong the churn.

<sub>🦉 via [talyn.dev](https://talyn.dev)</sub>

**Comment by Gilbert09** [comment]
### CI status update

This PR is approved with no open review threads. The only red required check is **Python code quality** (`mypy .`), and it is failing on an error that is **not related to this PR**:

```
products/exports/backend/temporal/subscriptions/ai_subscription/test/test_report_pipeline.py:487:
error: Missing named argument "relevant_events" for "_plan_to_freeze"  [call-arg]
```

This is a repo-wide `mypy` break currently on `master` — a semantic conflict between #71834 (which made `relevant_events` a required keyword argument of `_plan_to_freeze`) and #71837 (which added a `_plan_to_freeze` call site without it). Each PR was green on its own; combined on `master` they break `mypy .`, so this fails on every open PR, not just this one.

This branch only touches `products/warehouse_sources/.../metaplane/*`, and its tests pass locally (46 passed). No change is needed here — the check will go green once the `master`-side fix lands and this branch re-syncs (it is being kept up to date automatically). Monitoring for that.

<sub>🦉 via [talyn.dev](https://talyn.dev)</sub>

**Comment by Gilbert09** [comment]
Update: the master-side fix landed independently in [#71971](https://github.com/PostHog/posthog/pull/71971), and this branch has since merged master. Because that fix is identical to the one here, the `test_report_pipeline.py` change no longer shows in this PR's diff — it's back to Metaplane-only. Nothing further needed on that front.

<sub>🦉 via [talyn.dev](https://talyn.dev)</sub>

File: products/warehouse_sources/backend/temporal/data_imports/sources/metaplane/metaplane.py [hunk 1]
```diff
@@ -0,0 +1,334 @@
...
+    endpoint: str,
+    logger: FilteringBoundLogger,
+    resumable_source_manager: ResumableSourceManager[MetaplaneResumeConfig],
+    should_use_incremental_field: bool = False,
+    db_incremental_field_last_value: Any = None,
+) -> Iterator[list[dict[str, Any]]]:
+    headers = _get_headers(api_key)
+    # One session reused across every request so urllib3 keeps the connection alive
+    # instead of re-handshaking per request.
+    session = make_tracked_session()
```
[the remark this answers is not in the document]
Comment (Gilbert09) [reply products/warehouse_sources/backend/temporal/data_imports/sources/metaplane/metaplane.py]: Fixed in 7e896dd. All Metaplane traffic (both the credential probe and the sync) now goes through a shared session created with `capture=False`, so response bodies — which carry user-supplied monitor descriptions, `config` (custom SQL/where clauses), and evaluation/sync error messages — are excluded from the shared HTTP sample store. Added `redact_values=(api_key,)` as defense in depth and a test asserting sample capture is disabled.

<sub>🦉 via [talyn.dev](https://talyn.dev)</sub>

**Comment by Gilbert09** [comment]
**CI status note (automated)**

This branch is being brought up to date with `master` very frequently. Each update starts a fresh CI run and cancels the previous in-progress one (`cancel-in-progress` concurrency), so no run has been able to reach a green terminal state — the checks that intermittently show as failed are the aggregate `*Pass` gate jobs, which fail fast when their upstream jobs get cancelled mid-flight, not genuine test failures.

The change itself is verified green:
- Local test suite passes (46/46 in `products/warehouse_sources/backend/temporal/data_imports/sources/metaplane/tests/`).
- `ruff check` and `ruff format --check` are clean on the new files.
- Patch coverage is 98% per the CI report.
- On the runs that aren't cancelled, the actual Python / Node.js / Rust / Proto jobs succeed.

No code changes are required. The branch is mergeable (no conflicts, up to date with `master`), review threads are resolved, and the PR is approved. Once the branch stops being auto-updated for one full CI cycle — or it's merged through a queue that runs CI once — the checks should settle green.

<sub>🦉 via [talyn.dev](https://talyn.dev)</sub>
