### PR TITLE
fix(mysql): don't capture known connection errors during credential validation

### PR DESCRIPTION
**Pull request by Gilbert09**
## Problem

PostHog error tracking surfaced a `ConnectionRefusedError` (`[Errno 111] Connection refused`) originating in the MySQL data-warehouse source: [issue](https://us.posthog.com/project/2/error_tracking/019ed0ce-39e6-7ee3-aa33-b9fdd9be4234).

The stack shows it raised in `mysql.py:380` (`connect`), propagating through `get_schemas` into `MySQLSource.validate_credentials` (`source.py`). The originating request was the `external_data_sources/database_schema` endpoint — i.e. a user setting up a source, with their MySQL server unreachable. pymysql wraps the refusal as `OperationalError(2003, "Can't connect to MySQL server on '<host>' (...)")`.

`validate_credentials` already handles this gracefully: it catches the exception and returns a friendly "Could not connect... please check all connection details" message to the user. The problem is it *also* calls `capture_exception(e)` for **every** exception, so expected user/upstream connection failures (server down, wrong host/port, firewall, bad password) are reported to error tracking as if they were bugs.

## Changes

This is the credential-validation path, not the Temporal import workflow — `get_non_retryable_errors` (consumed only in `external_data_job.py`) never runs here, and `"Can't connect to MySQL server on"` is already classified non-retryable for the import path. So the fix is not to extend `NonRetryableErrors`; it is to stop capturing the already-recognised, already-handled user error.

- `validate_credentials` now only calls `capture_exception` when the error is **not** already classified as user-recoverable. A new `_is_known_user_error` helper reuses the source's existing `get_non_retryable_errors()` registry, so credential validation and the import pipeline agree on what counts as a user/upstream failure.
- Unrecognised exceptions are still captured, so genuine bugs in our connection code stay visible.

This mirrors an existing convention in this source — the COUNT(*) probe and EXPLAIN helper in `mysql.py` already deliberately avoid flooding error tracking with handled failures.

## How did you test this code?

I'm an agent. Dependencies aren't installed in my environment, so I could not run the full pytest suite here. I:

- Added a regression test class `TestValidateCredentialsCapture` asserting `capture_exception` is **not** called for known user errors (connection refused, access denied, host blocked) and **is** called for an unexpected `RuntimeError`.
- Verified both edited files compile (`py_compile`) and pass `ruff check` + `ruff format --check`.
- Validated the substring-matching logic in isolation against the exact error message from the error-tracking event — `"Can't connect to MySQL server on"` is recognised, while an unexpected message is not.

Please run `pytest posthog/temporal/data_imports/sources/mysql/tests/test_mysql.py::TestValidateCredentialsCapture` in CI to confirm.

## 🤖 Agent context

**Autonomy:** Fully autonomous

Triaged from an error-tracking webhook for the MySQL import source. Investigated via the PostHog error-tracking MCP tools: confirmed the issue, pulled the full stack trace and a representative event, and traced the call path to `validate_credentials` reached via the `database_schema` API endpoint (not the import pipeline).

Decision: the underlying `ConnectionRefusedError` is a user/upstream failure, but it is already handled gracefully and already non-retryable for the import path — so extending `NonRetryableErrors` would be a no-op for this event. The real defect is `validate_credentials` capturing an expected, already-recognised user error as an exception. Fixed at that layer, reusing the existing non-retryable registry rather than introducing a new classification.

---

> [!NOTE]
> Adds a test case for MySQL OperationalError 1129 ("Host is blocked") and fixes the Postgres server-cursor test mock by adding the missing `broken` attribute that was causing CI failures.
> 
> <sup>Written by [Mendral](https://mendral.com) for commit d45c97575b3f9f31a6fb70f797175956b6960d7c.</sup>

### CODE REVIEW

**Comment by Gilbert09** [comment]
This change has been superseded by #64029 ("fix(mysql): stop capturing expected connection errors during validation"), which was merged to master earlier today and implements the same fix.

Both PRs gate `capture_exception` in `MySQLSource.validate_credentials` on whether the error is already classified as non-retryable via `get_non_retryable_errors()`, so expected user/upstream connection failures (unreachable host, refused connection, blocked host, access denied, …) no longer flood error tracking, while genuinely unexpected errors are still captured.

The merged version is a strict superset of this one:
- It also returns the **pattern-specific** friendly error message for recognised failures (this PR always returned the generic "Could not connect…" message).
- It ships equivalent coverage via `TestMySQLSourceValidateCredentials` (known errors not captured; unexpected errors still captured).

As a result, rebasing this branch onto master produces no meaningful diff — the inline implementation on master already contains this PR's intent. Rather than reintroduce a competing refactor (a `_is_known_user_error` helper) or duplicate tests onto freshly-merged code, I'd recommend **closing this PR as a duplicate of #64029**.

If you'd instead like to keep the helper extraction as a follow-up cleanup, let me know and I'll rework it on top of the merged version without regressing the pattern-specific messages.

**Comment by Gilbert09** [comment]
## Superseded by #64029 — recommend closing

While bringing this branch up to date I found that the identical fix already landed on `master` via **#64029** (`dccc8bf3`, merged shortly after this PR's commit). It touches the same two files (`mysql/source.py` + `mysql/tests/test_mysql.py`) and solves the same problem — skipping `capture_exception` in `validate_credentials` for failures already classified by `get_non_retryable_errors()`.

The merge conflict here is a direct head-on overlap of two implementations of the same fix. Comparing this branch against current `master`:

- **Functionally equivalent** on the core behavior (don't capture known user/upstream connection errors).
- **#64029 is slightly better on UX:** when an error matches a known pattern it returns that pattern's *specific* friendly message (`friendly_error or …`). This PR returns a generic "Could not connect…" message in all cases. So merging this PR on top of `master` would actually *regress* the user-facing error message.
- #64029 also reads the message from `e.args` (`" ".join(...)`) rather than `str(e)`, which is a touch more robust.

Given the fix is already on `master` and the only ways to make this branch "mergeable" are either an empty no-op (taking master's version) or forcing redundant churn (a second test class duplicating master's, plus a helper duplicating logic already inline on master), I did **not** force a merge — that would add nothing or regress the codebase.

**Recommendation: close this PR as superseded by #64029.** Happy to repurpose it instead (e.g. a small refactor extracting master's inline classification loop into a documented helper) if you'd prefer to keep it open — just let me know.

(Note: the automated gate also flagged this PR for human review on @PostHog/team-warehouse-sources; that's a separate process gate I can't resolve in code.)

**Review by MarconLP — APPROVED** [review]

**Comment by Gilbert09** [comment]
Heads up: while this PR was open, master independently shipped an equivalent (and slightly more complete) fix in `MySQLSource.validate_credentials` — it iterates `get_non_retryable_errors()`, returns the specific friendly message per matched pattern, and skips `capture_exception` for known user/upstream failures. It also added a `TestMySQLSourceValidateCredentials` test class covering the same behavior.

To avoid duplicating that work, I rebased and resolved the conflict by adopting master's implementation and dropping the now-redundant `_is_known_user_error` helper and the duplicate `TestValidateCredentialsCapture` class. The only remaining delta this PR contributes is the one error case master's tests didn't cover — the `1129` 'host is blocked' error — folded into master's existing parametrized test. The PR's original intent (don't capture known connection errors during credential validation) is fully satisfied by master.

**Comment by Gilbert09** [comment]
CI note: the only failing check (`Django tests – Temporal (10/11)`) was failing on **master itself**, not from this change. `TestServerCursorStatementTimeout` (added in #63807) uses a `_Connection` mock that lacks a `broken` attribute, while `_raise_if_setup_connection_broken` (added in #63810) reads `connection.broken` on the `get_rows` path the test exercises. Each PR was green alone; together they raise `AttributeError: '_Connection' object has no attribute 'broken'`. I added a one-line `broken = False` to the mock (mirroring its existing `closed`/`autocommit` defaults) to unblock the shared Temporal test shard. Slightly out of scope for a mysql change, but it's the failing required check and a trivial, correct fix.

**Comment by Gilbert09** [comment]
Update: master shipped the same postgres mock fix in #63743, so I've dropped my redundant `broken = False` commit and rebased. The PR is now back to its single intended change — the `1129` blocked-host case added to MySQL's `test_known_connection_errors_are_not_captured`. The Temporal test shard is green on the latest run now that master carries the postgres fix.
