### ISSUE TITLE
worker: 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by FUSAKLA** [PostHog/posthog#2598]
## Bug description

After upgrading to 1.18.0 I noticed these tracebacks in the worker logs. But it is possible it was happening before, unfortunately I do not have longer retention logs. :/ But It probably happens just for some tasks because otherwise the events are processed.

```
[2020-12-01 11:30:38,761: ERROR/MainProcess] pidbox command error: AttributeError("'NoneType' object has no attribute 'groups'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/kombu/pidbox.py", line 104, in dispatch
    reply = handle(method, arguments)
  File "/usr/local/lib/python3.8/site-packages/kombu/pidbox.py", line 126, in handle_cast
    return self.handle(method, arguments)
  File "/usr/local/lib/python3.8/site-packages/kombu/pidbox.py", line 120, in handle
    return self.handlers[method](self.state, **arguments)
  File "/usr/local/lib/python3.8/site-packages/celery/worker/control.py", line 279, in enable_events
    if dispatcher.groups and 'task' not in dispatcher.groups:
AttributeError: 'NoneType' object has no attribute 'groups'
```
I'm wondering if anyone bumped into this also?

## Environment
Self-hosted Posthog instance running in Kubernetes in version 1.18.0 using the upstream Docker image.

**Comment by mariusandra** [comment]
Hey @FUSAKLA - we haven't seen anything like this elsewhere. That said, we did make some changes to celery in `1.18`. We removed its [`gossip`, `heartbeat` and `mingle`](https://stackoverflow.com/questions/55249197/what-are-the-consequences-of-disabling-gossip-mingle-and-heartbeat-for-celery-w) services to reduce the number of used Redis connections the workers consume. PostHog doesn't depend on these parts of Celery. However since the release we have learned that if you're using [celery-prometheus-exporter](https://github.com/PostHog/posthog/issues/2607), `gossip` must be enabled. Perhaps you are running into a similar problem?

**Comment by mariusandra** [comment]
Haha, should have checked the username :). Please ignore.

**Comment by FUSAKLA** [comment]
:) Yes, I suspect that It's most probably not an issue in the Posthog codebase.
I'd suspect some version upgrade of celery or some system libraries but none of those changed. 
The setup is running in Kubernetes  using Redis 5.0.5 and PostgreSQL with custom manifests based on the rendered official helm chart.

I wanted to check if anyone else did not bump into the same issue. Will wait and try it out with the gossip etc enabled and possibly somehow narrow down what could be the cause. I'll close this for now and paste the solution if I manage to find it.

**Comment by mariusandra** [comment]
Hey, I guess this is resolved after https://github.com/PostHog/posthog/pull/2621 ? Closing the issue for now, please reopen if there's still something to do.

**Comment by FUSAKLA** [comment]
Yes, thank you!
